# 数据库连接字符串
connectionString: mongodb://localhost:27017
dataBase: "config"
serverPort: "8080"

auth:
  privateKey: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAr4m0kO0v4V+2oUSnUIUvPsSAssCO4DAw2BTFsCWiyh68wrOt
    I6zkdAypBUsDUU6CLZNk6knLMrQMGrIeXlmK3nvA8DvbolwN134XhFBXjLlkAmIF
    bg5VaFKynLiYOUgJnhJkBcCavFM7Pq9AmqYeLsQzBJZxc6J33kFo9DQS1E0zrTaA
    MU33Mx/386u9xPcMtueLEOASTc2eShwMLWwstriINj3moVXV/KCj5U2PucTcGCNU
    UNl01iBM2iEFJq/Ar5lWbn36TWteu1Fypc0rR6IwskCGr6Jn1FTNtvvVPdrd4PEF
    dkMCr2WX1W6TtqDHvgJFT44WV6VogZ23bvl26wIDAQABAoIBAAq2DWWWg4huDbfT
    d54rMlHTLcM6ir1VU3Wr9tAjy8Ynj/8VdagqoZoPN7UR+bbZYoojZ1IAhLyoTeDH
    I6FAN4AR7xj5nhJPKa0PjaHOQTleCqM2lfw8Navy9+EmRmugYK3bk2zibs61CXVu
    vjNxlX/nCvHpuCyFKmlOdngIQWng3i+r9k+F8jBiV2s2+eJeLDCZF7k6M2qs6MTK
    V0wUtDLdvfJ5+8+/gMipFk9byKNOf79s5i5GNSPwCk6NLX3vHIW+ftBuemOu0Qu3
    j+NQS/g/c7I9cksZ5goWAIR0YP48cmlCPJwykxLcEhOZRt+LcFCCdZaW0H1pqlWl
    1HrWFFECgYEA4HUL9Kj7YWwlWQw0cqB6diKUYqMksIHWwyiwOexY0l+wDrzuDSw5
    7fJtHAwZ+5bpdJN1J3f1+8QZpx6CcZEK+818tZJfQLsfVStlfIzBKMFJzD4o9Fqm
    n5WcbeIta1TWlHvXWmcUdjClQXNx2594AGRWP726BQ45SUJFU8jaluMCgYEAyDTD
    i1+XjHlLKlwDi9c3OSF2SDlfKGHeb/yrQWxJTOyUCpWMIlMpD0VsooO77tdPNLHF
    LqDp6Xkk6UvAoVdA3/ik8ltdeNdLB8yysTl9v4d4d85Ycx8BeHtnnI2gjLIQFpXG
    ZEs3jsWbmKkWGm4zenhqA9aOSPdYCYamCFHGllkCgYEAjb4cgLI9nPYYV7V3YXOq
    IfQQVIHF55j2sGN/dfSk2qUGnyf8BGGLa5IOCQozVkekwbNk5jnBIu5hbMG9ik4X
    64+GU3tNn6kLTlOLUS3pxPzax5nxbu3YDysBj/qmyALZRwc1pac2qrRph32JxzFb
    LJQwSyxazlp/Hp40/YX3VBUCgYBFc8BuRiAdtCo2LKtyRJu8rvYIghaXvLPcp4uF
    a5pWHDATJ+PwOGcjDBNuoUJ9zaWFgzIDRgE/ZC5A3G2bytgPmoMmLDnV5OH7d7B5
    uJb97XIGJcgbT6ND95NvBNawWEkqfJTRUCKa3cRnhijLzHUBRGqKoFDF0UByNYq9
    khjRKQKBgH4ERyyYE9by/fph4MQQBanf3z2oqEXtnCyyWvMZDIofTBk5YoXP1Lq7
    q3Dv+aWJTjYshvcTumtymLdUKKulsixoBzLNe99gfeuSWwplYO3h7bk7irNngr12
    1zxA3jlO4+mLIiPfhOyluyJh5lxOlsEfO/Vrs3eJJH7pIQlpuNJf
    -----END RSA PRIVATE KEY-----

  publicKey: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr4m0kO0v4V+2oUSnUIUv
    PsSAssCO4DAw2BTFsCWiyh68wrOtI6zkdAypBUsDUU6CLZNk6knLMrQMGrIeXlmK
    3nvA8DvbolwN134XhFBXjLlkAmIFbg5VaFKynLiYOUgJnhJkBcCavFM7Pq9AmqYe
    LsQzBJZxc6J33kFo9DQS1E0zrTaAMU33Mx/386u9xPcMtueLEOASTc2eShwMLWws
    triINj3moVXV/KCj5U2PucTcGCNUUNl01iBM2iEFJq/Ar5lWbn36TWteu1Fypc0r
    R6IwskCGr6Jn1FTNtvvVPdrd4PEFdkMCr2WX1W6TtqDHvgJFT44WV6VogZ23bvl2
    6wIDAQAB
    -----END PUBLIC KEY-----